### ISSUE TITLE
Continuously Receive Return to Solum Dialog

### ISSUE THREAD

**Issue by thebigh2014** [Adde-Endless-Sky/AES-Irm#1]
Any time after I have "taken the device", including **immediately after**, I get the `Return to Solum` conversation and every landing afterward (even without and after the `Return to Solum` mission.  This is with latest download and I'm playing on Continuous.

**Comment by Darcman99** [comment]
[Fixed](https://github.com/Adde-Endless-Sky/AES-Irm/commit/46289c47b6b548e50a3c3f089074f159da3178b9). Thank you for reporting this bug!
